Задача - перевод подмодуля проведения контрольных на Spring MVC
SergeyShkuratko/SchoolMark pull request #70
Opened 2017-10-27 13:30 UTC by nadeevkm

Перевел подмодуль проведения контрольных работ на Spring MVC

2017-10-27 13:47 UTC, vnshakirov requested changes

2017-10-27 13:47 UTC, Crazy1305 commented on auth/src/main/webapp/META-INF/context.xml
> +              maxActive="100"
Надо вернуть настройки общего модуля обратно

2017-10-27 13:47 UTC, Crazy1305 commented on organizer/src/main/java/inno/controllers/NewTestController.java
> +    private Logger logger;
А зачем ты убрал static-и у логгеров? Теперь будет на каждый экземпляр класса по экземпляру логера.

2017-10-27 13:47 UTC, Crazy1305 commented on organizer/src/main/java/inno/servlets/RunTestServlet.java
> +//@WebServlet("/test-run")
Серлет еще нужен? Если нет, то надо удалить его

2017-10-27 14:15 UTC, nadeevkm commented on organizer/src/main/java/inno/controllers/NewTestController.java
> +    private Logger logger;
После перевода на spring сейчас у нас все синглтон по дефолту и следовательно будет один экземпляр каждого класса. Если планируем менять скоупы, я переделаю. Если нет - то так выглядит лучше.

2017-10-27 14:16 UTC, nadeevkm commented on auth/src/main/webapp/META-INF/context.xml
> +              maxActive="100"
Хорошо

2017-10-27 14:22 UTC, Crazy1305 commented on organizer/src/main/java/inno/controllers/NewTestController.java
> +    private Logger logger;
Пока оставим, уточнить у Артема

2017-10-29 13:09 UTC, vnshakirov approved these changes

2017-10-29 13:11 UTC, merged